[Error] 2020-01-24 11:43:21 Failed to connect to MySQL:Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot.

[Error] 2020-01-28 13:03:12 Failed to connect to MySQL:Access denied for user 'phpalapok*'@'localhost' (using password: YES)
